CREATE TABLE IF NOT EXISTS TASK
(
  ID          SERIAL NOT NULL,
  TITLE          VARCHAR(100),
  DESCRIPTION    VARCHAR(200),
  STATUS         VARCHAR(50),
  FIRST_USER  VARCHAR(50),
  SECOND_USER VARCHAR(50),
  THIRD_USER  VARCHAR(50),
  PRIMARY KEY (ID)
);